name: Continuos Integration

on: pull_request

jobs: 
    continuos-integration:
        runs-on: ubunto-latest
        steps:
            - uses: actions/checkout@v3
            - name: Using Node.js
              uses: actions/setup-node@v2
              with: 
                node-version: 23.
            - name: run install,build and test
              run : | 
                  npm install
                  npm run build
                  npm run test