version: "3.9"

services:

  user-frontend:
    image: apg2000/eletranet-frontend:latest
    ports:
      - '3001:5173'
    networks:
      - backend_network
    depends_on:
      - backend

  backend:
    image: apg2000/eletranet-backend:latest
    ports:
      - '8081:8080'
    networks:
      - backend_network
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tqs
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./Postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network

volumes:
  postgres_db:

networks:
  backend_network:
    driver: bridge

