version: "3.9"

services:

  user-frontend:
    build:
      context: ./client/EletranetFrontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_API: "http://localhost:8080"
    ports:
      - '3001:5173'
    networks:
      - backend_network
    depends_on:
      - backend

  backend:
    build:
      context: ./server/eletranet/backend
      dockerfile: Dockerfile
    volumes:
      - ./server/eletranet/backend:/Backend
    ports:
      - '8080:8080'
    networks:
      - backend_network
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tqs
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./Postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network

volumes:
  postgres_db:

networks:
  backend_network:
    driver: bridge
