# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

#on:
#  release:
#    types: [published]

name: Publish Docker images
on:
  push:
    branches: ['main']

jobs:
  build-backend-image:
    name: Push the Backend Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images:  ${{ secrets.DOCKER_USERNAME }}/eletranet-backend

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server/eletranet/backend
          file: ./server/eletranet/backend/Dockerfile
          push: true
          tags:  ${{ secrets.DOCKER_USERNAME }}/eletranet-backend:latest
          labels: ${{ steps.meta.outputs.labels }}

  build-user-frontend-image:
    name: Push the User-Frontend Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images:  ${{ secrets.DOCKER_USERNAME }}/eletranet-frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./client/EletranetFrontend
          file: ./client/EletranetFrontend/Dockerfile
          push: true
          tags:  ${{ secrets.DOCKER_USERNAME }}/eletranet-frontend:latest
          labels: ${{ steps.meta.outputs.labels }}


  deploy:
    runs-on: self-hosted
    name: "Deploy to VM"
    needs: [build-backend-image,   build-user-frontend-image]

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - name: "Deploy"
      run: |
          echo "CREATE DATABASE tqs_backend;" > init.sql
          sudo docker compose -f docker-compose.prod.yml pull
          sudo docker compose -f docker-compose.prod.yml up -d --remove-orphans
          sudo docker container prune -f
          sudo docker image prune -af
          sudo docker builder prune -af